-- MySQL Script generated by MySQL Workbench
-- 11/07/20 17:33:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cbms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cbms` ;

-- -----------------------------------------------------
-- Schema cbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cbms` DEFAULT CHARACTER SET utf8mb4 ;
USE `cbms` ;

-- -----------------------------------------------------
-- Table `cbms`.`asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`asset` ;

CREATE TABLE IF NOT EXISTS `cbms`.`asset` (
  `asset_id` INT(11) NOT NULL AUTO_INCREMENT,
  `unit_nb` INT(11) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `sn` VARCHAR(20) NULL DEFAULT NULL,
  `manufacturer` VARCHAR(20) NULL DEFAULT NULL,
  `category` VARCHAR(20) NULL DEFAULT NULL,
  `site` VARCHAR(20) NULL DEFAULT NULL,
  `location` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`asset_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`model` ;

CREATE TABLE IF NOT EXISTS `cbms`.`model` (
  `model_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`model_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`asset_model_calculation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`asset_model_calculation` ;

CREATE TABLE IF NOT EXISTS `cbms`.`asset_model_calculation` (
  `asset_id` INT(11) NOT NULL,
  `model_id` INT(11) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `value` DOUBLE NULL DEFAULT NULL,
  INDEX `fk_asset_model_calculation_asset1_idx` (`asset_id` ASC),
  INDEX `fk_asset_model_calculation_model1_idx` (`model_id` ASC),
  PRIMARY KEY (`model_id`, `asset_id`),
  CONSTRAINT `fk_asset_model_calculation_asset1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `cbms`.`asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_model_calculation_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `cbms`.`model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`dataset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`dataset` ;

CREATE TABLE IF NOT EXISTS `cbms`.`dataset` (
  `dataset_id` INT(11) NOT NULL AUTO_INCREMENT,
  `train` TINYINT(1) NULL DEFAULT NULL,
  `name` CHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`dataset_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`attribute` ;

CREATE TABLE IF NOT EXISTS `cbms`.`attribute` (
  `attribute_id` INT(11) NOT NULL AUTO_INCREMENT,
  `attribute_name` VARCHAR(50) NULL DEFAULT NULL,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  `location` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`attribute_measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`attribute_measurements` ;

CREATE TABLE IF NOT EXISTS `cbms`.`attribute_measurements` (
  `asset_id` INT(11) NOT NULL,
  `attribute_id` INT(11) NOT NULL,
  `time` INT(11) NOT NULL,
  `value` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`asset_id`, `attribute_id`, `time`),
  INDEX `sensor_nb` (`attribute_id` ASC),
  INDEX `fk_sensor_measurements_asset1_idx` (`asset_id` ASC),
  CONSTRAINT `measure_ibfk_2`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `cbms`.`attribute` (`attribute_id`),
  CONSTRAINT `fk_sensor_measurements_asset1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `cbms`.`asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`operational_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`operational_condition` ;

CREATE TABLE IF NOT EXISTS `cbms`.`operational_condition` (
  `oc_name` VARCHAR(50) NOT NULL,
  `oc_description` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`oc_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`dataset_condition_assoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`dataset_condition_assoc` ;

CREATE TABLE IF NOT EXISTS `cbms`.`dataset_condition_assoc` (
  `dataset_id` INT(11) NOT NULL,
  `oc_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`dataset_id`, `oc_name`),
  INDEX `oc_name` (`oc_name` ASC),
  CONSTRAINT `measured_in_ibfk_1`
    FOREIGN KEY (`dataset_id`)
    REFERENCES `cbms`.`dataset` (`dataset_id`),
  CONSTRAINT `measured_in_ibfk_2`
    FOREIGN KEY (`oc_name`)
    REFERENCES `cbms`.`operational_condition` (`oc_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cbms`.`dataset_asset_assoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbms`.`dataset_asset_assoc` ;

CREATE TABLE IF NOT EXISTS `cbms`.`dataset_asset_assoc` (
  `dataset_id` INT(11) NOT NULL,
  `asset_id` INT(11) NOT NULL,
  PRIMARY KEY (`dataset_id`, `asset_id`),
  INDEX `fk_dataset_asset_assoc_asset1_idx` (`asset_id` ASC),
  CONSTRAINT `fk_dataset_asset_assoc_dataset1`
    FOREIGN KEY (`dataset_id`)
    REFERENCES `cbms`.`dataset` (`dataset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataset_asset_assoc_asset1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `cbms`.`asset` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
